export {
  scoreSearchCandidates,
  scoreSearchCandidatesDetailed,
  validatePersonAtCompany,
  scoreRevealedCandidates,
  validateDataQuality,
  disambiguateEntity,
  decideMerge,
  generateOutreachBrief,
  generateCompanySummary,
  confidenceFromEntityMatch,
} from "./gates.js";
export type {
  Confidence,
  EntityMatch,
  RoleContext,
  ValidationResult,
  DisambiguationResult,
  PreliminaryScore,
  ScoreCandidatesResult,
  CandidateScore,
  DataQualityResult,
  MergeAction,
  MergeDecision,
} from "./types.js";
